# Generated by Django 4.0.3 on 2022-03-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boox_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='user',
            name='messenger',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Whatsapp'),
        ),
    ]
