# Generated by Django 4.0.3 on 2022-03-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boox_app', '0002_user_facebook_user_messenger_user_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wilaya',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Wilaya'),
        ),
    ]
