# Generated by Django 4.0.3 on 2022-03-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boox_app', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='goodread',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Goodread'),
        ),
    ]
