# Generated by Django 4.0.3 on 2022-04-13 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boox_app', '0009_book_wilaya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='goodread',
            new_name='goodreads',
        ),
    ]
