# Generated by Django 4.0.3 on 2022-04-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boox_app', '0010_rename_goodread_book_goodreads'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='messenger',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Messenger'),
        ),
        migrations.AddField(
            model_name='book',
            name='whatsup',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Whatsup'),
        ),
    ]
